name: Continuous Deployment (Prod)

on:
    push:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_SECRET }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push school image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: 100xdevs/scholl:${{ github.sha }} # Current sha of commit, docker image tag name

            - name: Cloning staging-ops repo, update image tags, and push tags
              env:
                  PAT: ${{ secrets.PAT }}
              run: |
                  git clone https://github.com/code100x/staging-ops.git
                  cd staging-ops

                  sed -i 's|image: 100xdevs/school:.*|image: 100xdevs/school:${{ github.sha }}|' prod/school/deployment.yml 

                  git config user.name "GitHub Actions Bot"
                  git config user.email "actions@github.com"
                  git add .
                  git commit -m "Update school server image tags to ${{ github.sha }}"
                  git push https://${PAT}@github.com/code100x/staging-ops.git main
                  
