kind: Cluster                      
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane            # Master node (manages the cluster)
  - role: worker                   # Worker node (runs application workloads)
  - role: worker                   # Worker node (runs application workloads)
