apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
      - name: ecom-backend
        image: 100xdevs/env-backend
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: dotfile-secret
              key: database_url
        - name: CACHE_SIZE
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: cache_size
        - name: PAYMENT_GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: payment_gateway_url
        - name: MAX_CART_ITEMS
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: max_cart_items
        - name: SESSION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: session_timeout



# kirat
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ecom-backend-deployment
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: ecom-backend
#   template:
#     metadata:
#       labels:
#         app: ecom-backend
#     spec:
#       containers:
#       - name: todo-backend
#         image: 100xdevs/todo-app-test:1
#         ports:
#         - containerPort: 3000
#         volumeMounts:
#         - name: env-file
#           readOnly: true
#           mountPath: "/app/secret"
#       volumes:
#       - name: env-file
#         secret:
#           secretName: backend-secret